### ISSUE TITLE
No rights to Create User | Error occurred while tyring to connect to API. 

### ISSUE THREAD

**Issue by Snogo** [crmcmullen/medium-php-api-starter#6]
first of all thank you very much for creating this starter RESTFUL API

however I have a problem getting it to run which might have to do with that I don't have the rights to CREATE USER on my webserver. apart from that I could run all the sql. when I want to open the client it says `Error occurred while tyring to connect to API.` however

can I also use your starter packages with my own db user (which can not be changed)? what changes do I have to do or do you think its another problem?

**Edit:** solved it for now. I had an unnecessary space inside the CONST_DB_HOST which was causing the connection problem

**Comment by crmcmullen** [comment]
I apologize, I just saw this issue.  I'm glad you got it resolved.
